name: Sync with Upstream

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Add Upstream Remote
        run: git remote add upstream https://github.com/G-Chandramani/aws_code_deploy_test.git

      - name: Fetch Changes from Upstream
        run: git fetch upstream

      - name: Merge Changes
        run: git merge upstream/main

      - name: Push Changes to Fork
        run: git push origin main
